/**
 * Permission Constants
 * Defines all permissions available in the system
 * Organized by resource with their actions (READ, WRITE, UPDATE, DELETE)
 */

export const PERMISSIONS = {
  // Admin Creation Permissions
  ADMIN_CREATION: {
    READ: 'ADMIN_CREATION:READ',
    WRITE: 'ADMIN_CREATION:WRITE',
    UPDATE: 'ADMIN_CREATION:UPDATE',
    DELETE: 'ADMIN_CREATION:DELETE',
  },

  // Booking Permissions
  BOOKING: {
    READ: 'BOOKING:READ',
    WRITE: 'BOOKING:WRITE',
    UPDATE: 'BOOKING:UPDATE',
    DELETE: 'BOOKING:DELETE',
  },

  // Room Management Permissions
  ROOM_MANAGEMENT: {
    READ: 'ROOM_MANAGEMENT:READ',
    WRITE: 'ROOM_MANAGEMENT:WRITE',
    UPDATE: 'ROOM_MANAGEMENT:UPDATE',
    DELETE: 'ROOM_MANAGEMENT:DELETE',
  },

  // Payment Processing Permissions
  PAYMENT_PROCESSING: {
    READ: 'PAYMENT_PROCESSING:READ',
    WRITE: 'PAYMENT_PROCESSING:WRITE',
    UPDATE: 'PAYMENT_PROCESSING:UPDATE',
    DELETE: 'PAYMENT_PROCESSING:DELETE',
  },

  // Refund Approval Permissions
  REFUND_APPROVAL: {
    READ: 'REFUND_APPROVAL:READ',
    WRITE: 'REFUND_APPROVAL:WRITE',
    UPDATE: 'REFUND_APPROVAL:UPDATE',
    DELETE: 'REFUND_APPROVAL:DELETE',
  },

  // Content Management Permissions
  CONTENT_MANAGEMENT: {
    READ: 'CONTENT_MANAGEMENT:READ',
    WRITE: 'CONTENT_MANAGEMENT:WRITE',
    UPDATE: 'CONTENT_MANAGEMENT:UPDATE',
    DELETE: 'CONTENT_MANAGEMENT:DELETE',
  },

  // Issue Resolution Permissions
  ISSUE_RESOLUTION: {
    READ: 'ISSUE_RESOLUTION:READ',
    WRITE: 'ISSUE_RESOLUTION:WRITE',
    UPDATE: 'ISSUE_RESOLUTION:UPDATE',
    DELETE: 'ISSUE_RESOLUTION:DELETE',
  },

  // Notification Handling Permissions
  NOTIFICATION_HANDLING: {
    READ: 'NOTIFICATION_HANDLING:READ',
    WRITE: 'NOTIFICATION_HANDLING:WRITE',
    UPDATE: 'NOTIFICATION_HANDLING:UPDATE',
    DELETE: 'NOTIFICATION_HANDLING:DELETE',
  },

  // Analytics View Permissions
  ANALYTICS_VIEW: {
    READ: 'ANALYTICS_VIEW:READ',
    WRITE: 'ANALYTICS_VIEW:WRITE',
    UPDATE: 'ANALYTICS_VIEW:UPDATE',
    DELETE: 'ANALYTICS_VIEW:DELETE',
  },

  // Backup Operations Permissions
  BACKUP_OPERATIONS: {
    READ: 'BACKUP_OPERATIONS:READ',
    WRITE: 'BACKUP_OPERATIONS:WRITE',
    UPDATE: 'BACKUP_OPERATIONS:UPDATE',
    DELETE: 'BACKUP_OPERATIONS:DELETE',
  },

  // Restore Operations Permissions
  RESTORE_OPERATIONS: {
    READ: 'RESTORE_OPERATIONS:READ',
    WRITE: 'RESTORE_OPERATIONS:WRITE',
    UPDATE: 'RESTORE_OPERATIONS:UPDATE',
    DELETE: 'RESTORE_OPERATIONS:DELETE',
  },

  // Offer Management Permissions
  OFFER_MANAGEMENT: {
    READ: 'OFFER_MANAGEMENT:READ',
    WRITE: 'OFFER_MANAGEMENT:WRITE',
    UPDATE: 'OFFER_MANAGEMENT:UPDATE',
    DELETE: 'OFFER_MANAGEMENT:DELETE',
  },
};

/**
 * Flat list of all permissions for easy iteration
 * Total: 48 permissions (12 resources × 4 actions each)
 */
export const ALL_PERMISSIONS = [
  // Admin Creation (4)
  PERMISSIONS.ADMIN_CREATION.READ,
  PERMISSIONS.ADMIN_CREATION.WRITE,
  PERMISSIONS.ADMIN_CREATION.UPDATE,
  PERMISSIONS.ADMIN_CREATION.DELETE,

  // Booking (4)
  PERMISSIONS.BOOKING.READ,
  PERMISSIONS.BOOKING.WRITE,
  PERMISSIONS.BOOKING.UPDATE,
  PERMISSIONS.BOOKING.DELETE,

  // Room Management (4)
  PERMISSIONS.ROOM_MANAGEMENT.READ,
  PERMISSIONS.ROOM_MANAGEMENT.WRITE,
  PERMISSIONS.ROOM_MANAGEMENT.UPDATE,
  PERMISSIONS.ROOM_MANAGEMENT.DELETE,

  // Payment Processing (4)
  PERMISSIONS.PAYMENT_PROCESSING.READ,
  PERMISSIONS.PAYMENT_PROCESSING.WRITE,
  PERMISSIONS.PAYMENT_PROCESSING.UPDATE,
  PERMISSIONS.PAYMENT_PROCESSING.DELETE,

  // Refund Approval (4)
  PERMISSIONS.REFUND_APPROVAL.READ,
  PERMISSIONS.REFUND_APPROVAL.WRITE,
  PERMISSIONS.REFUND_APPROVAL.UPDATE,
  PERMISSIONS.REFUND_APPROVAL.DELETE,

  // Content Management (4)
  PERMISSIONS.CONTENT_MANAGEMENT.READ,
  PERMISSIONS.CONTENT_MANAGEMENT.WRITE,
  PERMISSIONS.CONTENT_MANAGEMENT.UPDATE,
  PERMISSIONS.CONTENT_MANAGEMENT.DELETE,

  // Issue Resolution (4)
  PERMISSIONS.ISSUE_RESOLUTION.READ,
  PERMISSIONS.ISSUE_RESOLUTION.WRITE,
  PERMISSIONS.ISSUE_RESOLUTION.UPDATE,
  PERMISSIONS.ISSUE_RESOLUTION.DELETE,

  // Notification Handling (4)
  PERMISSIONS.NOTIFICATION_HANDLING.READ,
  PERMISSIONS.NOTIFICATION_HANDLING.WRITE,
  PERMISSIONS.NOTIFICATION_HANDLING.UPDATE,
  PERMISSIONS.NOTIFICATION_HANDLING.DELETE,

  // Analytics View (4)
  PERMISSIONS.ANALYTICS_VIEW.READ,
  PERMISSIONS.ANALYTICS_VIEW.WRITE,
  PERMISSIONS.ANALYTICS_VIEW.UPDATE,
  PERMISSIONS.ANALYTICS_VIEW.DELETE,

  // Backup Operations (4)
  PERMISSIONS.BACKUP_OPERATIONS.READ,
  PERMISSIONS.BACKUP_OPERATIONS.WRITE,
  PERMISSIONS.BACKUP_OPERATIONS.UPDATE,
  PERMISSIONS.BACKUP_OPERATIONS.DELETE,

  // Restore Operations (4)
  PERMISSIONS.RESTORE_OPERATIONS.READ,
  PERMISSIONS.RESTORE_OPERATIONS.WRITE,
  PERMISSIONS.RESTORE_OPERATIONS.UPDATE,
  PERMISSIONS.RESTORE_OPERATIONS.DELETE,

  // Offer Management (4)
  PERMISSIONS.OFFER_MANAGEMENT.READ,
  PERMISSIONS.OFFER_MANAGEMENT.WRITE,
  PERMISSIONS.OFFER_MANAGEMENT.UPDATE,
  PERMISSIONS.OFFER_MANAGEMENT.DELETE,
];

/**
 * Resources grouped by name
 * Useful for UI organization and permission management
 */
export const PERMISSION_RESOURCES = [
  { name: 'Admin Creation', key: 'ADMIN_CREATION' },
  { name: 'Booking Management', key: 'BOOKING' },
  { name: 'Room Management', key: 'ROOM_MANAGEMENT' },
  { name: 'Payment Processing', key: 'PAYMENT_PROCESSING' },
  { name: 'Refund Approval', key: 'REFUND_APPROVAL' },
  { name: 'Content Management', key: 'CONTENT_MANAGEMENT' },
  { name: 'Issue Resolution', key: 'ISSUE_RESOLUTION' },
  { name: 'Notification Handling', key: 'NOTIFICATION_HANDLING' },
  { name: 'Analytics View', key: 'ANALYTICS_VIEW' },
  { name: 'Backup Operations', key: 'BACKUP_OPERATIONS' },
  { name: 'Restore Operations', key: 'RESTORE_OPERATIONS' },
  { name: 'Offer Management', key: 'OFFER_MANAGEMENT' },
];

/**
 * Action order for consistent UI display
 */
export const ACTION_ORDER = ['READ', 'WRITE', 'UPDATE', 'DELETE'];
