"""init base schema

Revision ID: c7f919222ca5
Revises: 
Create Date: 2025-11-07 22:53:37.245331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f919222ca5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_tax_map')
    op.drop_index(op.f('idx_refunds_booking_status'), table_name='refunds')
    op.drop_index(op.f('idx_refunds_initiated_at'), table_name='refunds')
    op.drop_index(op.f('idx_refunds_is_deleted'), table_name='refunds', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_refunds_user'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('idx_edit_bookings_booking_type'), table_name='edit_bookings')
    op.drop_index(op.f('idx_edit_bookings_is_deleted'), table_name='edit_bookings', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_edit_bookings_requested_at'), table_name='edit_bookings')
    op.drop_index(op.f('idx_edit_bookings_status'), table_name='edit_bookings')
    op.drop_table('edit_bookings')
    op.drop_index(op.f('idx_rooms_type_status'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('idx_room_amenity_map_room_amenity'), table_name='room_amenity_map')
    op.drop_table('room_amenity_map')
    op.drop_index(op.f('idx_room_types_name'), table_name='room_types')
    op.drop_index(op.f('idx_room_types_price'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_index(op.f('idx_images_entity'), table_name='images')
    op.drop_index(op.f('idx_images_is_deleted'), table_name='images', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_images_is_primary'), table_name='images')
    op.drop_index(op.f('idx_images_uploaded_by'), table_name='images')
    op.drop_table('images')
    op.drop_table('payment_method_utility')
    op.drop_table('roles_utility')
    op.drop_index(op.f('idx_wishlist_added_at'), table_name='wishlist')
    op.drop_index(op.f('idx_wishlist_is_deleted'), table_name='wishlist', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_wishlist_offer'), table_name='wishlist')
    op.drop_index(op.f('idx_wishlist_user_room'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_wishlist_id'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('idx_issues_booking_status'), table_name='issues')
    op.drop_index(op.f('idx_issues_is_deleted'), table_name='issues', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_issues_reported_at'), table_name='issues')
    op.drop_index(op.f('idx_issues_user'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('idx_booking_room_map_booking'), table_name='booking_room_map')
    op.drop_index(op.f('idx_booking_room_map_flags'), table_name='booking_room_map')
    op.drop_index(op.f('idx_booking_room_map_room'), table_name='booking_room_map')
    op.drop_table('booking_room_map')
    op.drop_table('status_utility')
    op.drop_index(op.f('idx_permissions_resource_type'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('refund_room_map')
    op.drop_index(op.f('idx_sessions_last_active'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_active'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('blacklisted_tokens')
    op.drop_table('verifications')
    op.drop_index(op.f('idx_offers_created_by'), table_name='offers')
    op.drop_index(op.f('idx_offers_date_range'), table_name='offers')
    op.drop_index(op.f('idx_offers_is_deleted'), table_name='offers', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_offers_name'), table_name='offers')
    op.drop_index(op.f('idx_offers_visibility_status'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('idx_payments_booking_status'), table_name='payments')
    op.drop_index(op.f('idx_payments_date'), table_name='payments')
    op.drop_index(op.f('idx_payments_is_deleted'), table_name='payments', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_payments_method'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('idx_issue_chat_issue'), table_name='issue_chat')
    op.drop_index(op.f('idx_issue_chat_sender'), table_name='issue_chat')
    op.drop_index(op.f('idx_issue_chat_sent_at'), table_name='issue_chat')
    op.drop_table('issue_chat')
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_deleted'), table_name='notifications', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_notifications_user_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('idx_room_amenities_name'), table_name='room_amenities')
    op.drop_table('room_amenities')
    op.drop_index(op.f('idx_permission_role_map_role_perm'), table_name='permission_role_map')
    op.drop_table('permission_role_map')
    op.drop_index(op.f('idx_reviews_booking_user'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_is_deleted'), table_name='reviews', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_room_type'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('offer_room_map')
    op.drop_index(op.f('idx_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_is_deleted'), table_name='bookings', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_bookings_offer'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_user_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_is_deleted'), table_name='users', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    op.drop_index(op.f('idx_users_role_status'), table_name='users')
    op.drop_table('users')
    op.drop_table('tax_utility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_utility',
    sa.Column('tax_id', sa.INTEGER(), server_default=sa.text("nextval('tax_utility_tax_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tax_id', name='tax_utility_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('Male', 'Female', 'Other', name='gender_types'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_password_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('loyalty_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('profile_image_url', sa.VARCHAR(length=150), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='users_created_by_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles_utility.role_id'], name='users_role_id_fkey'),
    sa.ForeignKeyConstraint(['status_id'], ['status_utility.status_id'], name='users_status_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone_number', name='users_phone_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_users_role_status'), 'users', ['role_id', 'status_id'], unique=False)
    op.create_index(op.f('idx_users_phone'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_users_is_deleted'), 'users', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), server_default=sa.text("nextval('bookings_booking_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('room_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIME(), server_default=sa.text("'12:00:00'::time without time zone"), autoincrement=False, nullable=True),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out_time', postgresql.TIME(), server_default=sa.text("'11:00:00'::time without time zone"), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offer_discount_percent', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'AVAILABLE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('primary_customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_customer_phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_customer_dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_pre_edit_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_post_edit_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], name='bookings_offer_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_bookings_user', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('booking_id', name='bookings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_bookings_user_status'), 'bookings', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_bookings_offer'), 'bookings', ['offer_id'], unique=False)
    op.create_index(op.f('idx_bookings_is_deleted'), 'bookings', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_bookings_created_at'), 'bookings', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('offer_room_map',
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actual_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('discounted_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('actual_price >= 0::numeric', name=op.f('offer_room_map_actual_price_check')),
    sa.CheckConstraint('discounted_price >= 0::numeric', name=op.f('offer_room_map_discounted_price_check')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], name=op.f('offer_room_map_offer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], name=op.f('offer_room_map_room_type_id_fkey')),
    sa.PrimaryKeyConstraint('offer_id', 'room_type_id', name=op.f('offer_room_map_pkey'))
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('rating_range')),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], name=op.f('reviews_admin_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('reviews_booking_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], name=op.f('reviews_room_type_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('reviews_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('review_id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('idx_reviews_room_type'), 'reviews', ['room_type_id'], unique=False)
    op.create_index(op.f('idx_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('idx_reviews_is_deleted'), 'reviews', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_reviews_created_at'), 'reviews', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_reviews_booking_user'), 'reviews', ['booking_id', 'user_id'], unique=False)
    op.create_table('permission_role_map',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name=op.f('permission_role_map_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles_utility.role_id'], name=op.f('permission_role_map_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('permission_role_map_pkey'))
    )
    op.create_index(op.f('idx_permission_role_map_role_perm'), 'permission_role_map', ['role_id', 'permission_id'], unique=False)
    op.create_table('room_amenities',
    sa.Column('amenity_id', sa.INTEGER(), server_default=sa.text("nextval('room_amenities_amenity_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('amenity_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('amenity_id', name='room_amenities_pkey'),
    sa.UniqueConstraint('amenity_name', name='room_amenities_amenity_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_room_amenities_name'), 'room_amenities', ['amenity_name'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_type', postgresql.ENUM('SYSTEM', 'PROMOTIONAL', 'REMINDER', 'TRANSACTIONAL', 'SECURITY', 'OTHER', name='notification_type'), server_default=sa.text("'OTHER'::notification_type"), autoincrement=False, nullable=False),
    sa.Column('entity_type', postgresql.ENUM('BOOKING', 'PAYMENT', 'REFUND', 'ISSUE', 'OFFER', 'REVIEW', 'WISHLIST', 'USER_ACCOUNT', 'SYSTEM', 'ROOM', name='entity_type_enum'), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.user_id'], name=op.f('notifications_recipient_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notifications_user_read'), 'notifications', ['recipient_user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('issue_chat',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], name=op.f('issue_chat_issue_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('issue_chat_sender_id_fkey')),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('issue_chat_pkey'))
    )
    op.create_index(op.f('idx_issue_chat_sent_at'), 'issue_chat', [sa.literal_column('sent_at DESC')], unique=False)
    op.create_index(op.f('idx_issue_chat_sender'), 'issue_chat', ['sender_id'], unique=False)
    op.create_index(op.f('idx_issue_chat_issue'), 'issue_chat', ['issue_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('method_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'SUCCESS'::character varying"), autoincrement=False, nullable=True),
    sa.Column('transaction_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('payments_booking_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_method_utility.method_id'], name=op.f('payments_method_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('payments_user_id_fkey')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('transaction_reference', name=op.f('payments_transaction_reference_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_payments_method'), 'payments', ['method_id'], unique=False)
    op.create_index(op.f('idx_payments_is_deleted'), 'payments', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_payments_date'), 'payments', [sa.literal_column('payment_date DESC')], unique=False)
    op.create_index(op.f('idx_payments_booking_status'), 'payments', ['booking_id', 'status'], unique=False)
    op.create_table('offers',
    sa.Column('offer_id', sa.INTEGER(), server_default=sa.text("nextval('offers_offer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('offer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offer_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('offer_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('visibility_status', sa.VARCHAR(length=50), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('offer_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.CheckConstraint('discount_percent >= 0::numeric', name='offers_discount_percent_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='offers_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('offer_id', name='offers_pkey'),
    sa.UniqueConstraint('offer_name', name='offers_offer_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_offers_visibility_status'), 'offers', ['visibility_status'], unique=False)
    op.create_index(op.f('idx_offers_name'), 'offers', ['offer_name'], unique=False)
    op.create_index(op.f('idx_offers_is_deleted'), 'offers', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_offers_date_range'), 'offers', ['start_date', 'expiry_date'], unique=False)
    op.create_index(op.f('idx_offers_created_by'), 'offers', ['created_by'], unique=False)
    op.create_table('verifications',
    sa.Column('verification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verification_type', postgresql.ENUM('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'PHONE_OTP', name='verification_type'), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('verifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verification_id', name=op.f('verifications_pkey'))
    )
    op.create_table('blacklisted_tokens',
    sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('token_type', postgresql.ENUM('ACCESS', 'REFRESH', name='token_type'), autoincrement=False, nullable=False),
    sa.Column('token_value_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('revoked_type', postgresql.ENUM('AUTOMATIC_EXPIRED', 'MANUAL_REVOKED', name='revoked_type'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('blacklisted_tokens_session_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('blacklisted_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', name=op.f('blacklisted_tokens_pkey')),
    sa.UniqueConstraint('token_value_hash', name=op.f('blacklisted_tokens_token_value_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('access_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('login_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_active', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('sessions_pkey')),
    sa.UniqueConstraint('jti', name=op.f('sessions_jti_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('refresh_token', name=op.f('sessions_refresh_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sessions_user_active'), 'sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_sessions_last_active'), 'sessions', [sa.literal_column('last_active DESC')], unique=False)
    op.create_table('refund_room_map',
    sa.Column('refund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refund_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('refund_room_map_booking_id_fkey')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.refund_id'], name=op.f('refund_room_map_refund_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('refund_room_map_room_id_fkey')),
    sa.PrimaryKeyConstraint('refund_id', 'booking_id', 'room_id', name=op.f('refund_room_map_pkey'))
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=21), autoincrement=False, nullable=False),
    sa.Column('permission_type', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('permission_id', name=op.f('permissions_pkey')),
    sa.UniqueConstraint('resource', 'permission_type', name=op.f('permissions_resource_action_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('resource', 'permission_type', name=op.f('unique_resource_permission'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_permissions_resource_type'), 'permissions', ['resource', 'permission_type'], unique=False)
    op.create_table('status_utility',
    sa.Column('status_id', sa.INTEGER(), server_default=sa.text("nextval('status_utility_status_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('status_id', name='status_utility_pkey'),
    sa.UniqueConstraint('status_code', name='status_utility_status_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('booking_room_map',
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adults', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('children', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=True),
    sa.Column('offer_discount_percent', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('is_pre_edited_room', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_post_edited_room', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_room_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('rating_given', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('edit_suggested_rooms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('booking_room_map_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('booking_room_map_room_id_fkey')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], name=op.f('booking_room_map_room_type_id_fkey')),
    sa.PrimaryKeyConstraint('booking_id', 'room_id', name=op.f('booking_room_map_pkey'))
    )
    op.create_index(op.f('idx_booking_room_map_room'), 'booking_room_map', ['room_id'], unique=False)
    op.create_index(op.f('idx_booking_room_map_flags'), 'booking_room_map', ['is_pre_edited_room', 'is_post_edited_room', 'is_room_active'], unique=False)
    op.create_index(op.f('idx_booking_room_map_booking'), 'booking_room_map', ['booking_id'], unique=False)
    op.create_table('issues',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reported_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('issues_booking_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], name=op.f('issues_resolved_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('issues_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('issues_user_id_fkey')),
    sa.PrimaryKeyConstraint('issue_id', name=op.f('issues_pkey'))
    )
    op.create_index(op.f('idx_issues_user'), 'issues', ['user_id'], unique=False)
    op.create_index(op.f('idx_issues_reported_at'), 'issues', [sa.literal_column('reported_at DESC')], unique=False)
    op.create_index(op.f('idx_issues_is_deleted'), 'issues', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_issues_booking_status'), 'issues', ['booking_id', 'status'], unique=False)
    op.create_table('wishlist',
    sa.Column('wishlist_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], name=op.f('wishlist_offer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], name=op.f('wishlist_room_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('wishlist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wishlist_id', name=op.f('wishlist_pkey'))
    )
    op.create_index(op.f('ix_wishlist_wishlist_id'), 'wishlist', ['wishlist_id'], unique=False)
    op.create_index(op.f('idx_wishlist_user_room'), 'wishlist', ['user_id', 'room_type_id'], unique=False)
    op.create_index(op.f('idx_wishlist_offer'), 'wishlist', ['offer_id'], unique=False)
    op.create_index(op.f('idx_wishlist_is_deleted'), 'wishlist', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_wishlist_added_at'), 'wishlist', [sa.literal_column('added_at DESC')], unique=False)
    op.create_table('roles_utility',
    sa.Column('role_id', sa.INTEGER(), server_default=sa.text("nextval('roles_utility_role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', name='roles_utility_pkey'),
    sa.UniqueConstraint('role_name', name='roles_utility_role_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('payment_method_utility',
    sa.Column('method_id', sa.INTEGER(), server_default=sa.text("nextval('payment_method_utility_method_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('method_id', name='payment_method_utility_pkey'),
    sa.UniqueConstraint('name', name='payment_method_utility_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('images',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name=op.f('images_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('images_pkey'))
    )
    op.create_index(op.f('idx_images_uploaded_by'), 'images', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_images_is_primary'), 'images', ['is_primary'], unique=False)
    op.create_index(op.f('idx_images_is_deleted'), 'images', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_images_entity'), 'images', ['entity_type', 'entity_id'], unique=False)
    op.create_table('room_types',
    sa.Column('room_type_id', sa.INTEGER(), server_default=sa.text("nextval('room_types_room_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('max_adult_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('max_child_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('price_per_night', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('square_ft', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('room_type_id', name='room_types_pkey'),
    sa.UniqueConstraint('type_name', name='room_types_type_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_room_types_price'), 'room_types', ['price_per_night'], unique=False)
    op.create_index(op.f('idx_room_types_name'), 'room_types', ['type_name'], unique=False)
    op.create_table('room_amenity_map',
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amenity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['room_amenities.amenity_id'], name=op.f('room_amenity_map_amenity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name=op.f('room_amenity_map_room_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id', name=op.f('room_amenity_map_pkey'))
    )
    op.create_index(op.f('idx_room_amenity_map_room_amenity'), 'room_amenity_map', ['room_id', 'amenity_id'], unique=False)
    op.create_table('rooms',
    sa.Column('room_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('room_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_status', postgresql.ENUM('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'FROZEN', name='room_status_enum'), autoincrement=False, nullable=False),
    sa.Column('freeze_reason', postgresql.ENUM('NONE', 'CLEANING', 'ADMIN_LOCK', 'SYSTEM_HOLD', name='freeze_reason_enum'), autoincrement=False, nullable=True),
    sa.Column('price_per_night', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_adult_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('max_child_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], name=op.f('rooms_room_type_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('room_id', name=op.f('rooms_pkey')),
    sa.UniqueConstraint('room_no', name=op.f('rooms_room_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_rooms_type_status'), 'rooms', ['room_type_id', 'room_status'], unique=False)
    op.create_table('edit_bookings',
    sa.Column('edit_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_customer_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('primary_customer_phno', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('primary_customer_dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edit_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('edit_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('lock_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('requested_room_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('chosen_room_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('edit_bookings_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chosen_room_type'], ['room_types.room_type_id'], name=op.f('edit_bookings_chosen_room_type_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], name=op.f('edit_bookings_requested_by_fkey')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], name=op.f('edit_bookings_reviewed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['status_utility.status_id'], name=op.f('edit_bookings_status_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('edit_bookings_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('edit_id', name=op.f('edit_bookings_pkey'))
    )
    op.create_index(op.f('idx_edit_bookings_status'), 'edit_bookings', ['edit_status'], unique=False)
    op.create_index(op.f('idx_edit_bookings_requested_at'), 'edit_bookings', [sa.literal_column('requested_at DESC')], unique=False)
    op.create_index(op.f('idx_edit_bookings_is_deleted'), 'edit_bookings', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_edit_bookings_booking_type'), 'edit_bookings', ['booking_id', 'edit_type'], unique=False)
    op.create_table('refunds',
    sa.Column('refund_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'INITIATED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('initiated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('transaction_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('refunds_booking_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_method_id'], ['payment_method_utility.method_id'], name=op.f('refunds_transaction_method_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('refunds_user_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('refund_id', name=op.f('refunds_pkey'))
    )
    op.create_index(op.f('idx_refunds_user'), 'refunds', ['user_id'], unique=False)
    op.create_index(op.f('idx_refunds_is_deleted'), 'refunds', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_refunds_initiated_at'), 'refunds', [sa.literal_column('initiated_at DESC')], unique=False)
    op.create_index(op.f('idx_refunds_booking_status'), 'refunds', ['booking_id', 'status'], unique=False)
    op.create_table('booking_tax_map',
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tax_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('booking_tax_map_booking_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['tax_utility.tax_id'], name=op.f('booking_tax_map_tax_id_fkey')),
    sa.PrimaryKeyConstraint('booking_id', 'tax_id', name=op.f('booking_tax_map_pkey'))
    )
    # ### end Alembic commands ###
